# Generated by Django 3.2.6 on 2023-02-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plans',
            field=models.ManyToManyField(to='plans.Plan'),
        ),
    ]
